name: "Print All Events"
on:
  workflow_dispatch:
  push:
  pull_request:
jobs: 
    echo:
      name: Print All
      runs-on: ubuntu-latest
      steps:
        - name: echo env
          env:
            ISSUE_TITLE: ${{ github.event.issue.title }}
            ISSUE_BODY: ${{ github.event.issue.body }}
            PR_TITLE: ${{ github.event.pull_request.title }}
            PR_BODY: ${{ github.event.pull_request.body }}
            PR_COMMENT : ${{ github.event.comment.body }}
            REVIEW_BODY: ${{ github.event.review.body }}
            PAGE_NAME: ${{ toJson(github.event.pages.*.page_name) }}
            COMMIT_MSG: ${{ toJson(github.event.commits.*.message) }}
            HEAD_COMMIT_MSG: ${{ github.event.head_commit.message }}
            EMAIL: ${{ github.event.head_commit.author.email }}
            NAME: ${{ github.event.head_commit.author.name }}
            COMMIT_EMAIL: ${{ toJson(github.event.commits.*.author.email) }}
            COMMIT_NAME: ${{ toJson(github.event.commits.*.author.name) }}
            PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
            PR_HEAD_LABEL: ${{ github.event.pull_request.head.label }}
            PR_DEFAULT_BRANCH: ${{ github.event.pull_request.head.repo.default_branch }}
            HEAD_REF: ${{ github.head_ref }}
            REF: ${{ github.ref }}
            REPO: ${{ github.repository }}
            EVENT: ${{ toJson(github.event) }}
          run: |
            echo "github.event.issue.title ==>" ${ISSUE_TITLE}
            echo "github.event.issue.body ==>" ${ISSUE_BODY}
            echo "github.event.pull_request.title ==>" ${PR_TITLE}
            echo "github.event.pull_request.body ==>" ${PR_BODY}
            echo "github.event.comment.body ==>" ${PR_COMMENT}
            echo "github.event.review.body ==>" ${REVIEW_BODY}
            echo "github.event.pages.*.page_name ==>" ${PAGE_NAME}
            echo "github.event.commits.*.message ==>" ${COMMIT_MSG}
            echo "github.event.head_commit.message ==>" ${HEAD_COMMIT_MSG}
            echo "github.event.head_commit.author.email ==>" ${EMAIL}
            echo "github.event.head_commit.author.name ==>" ${NAME}
            echo "github.event.commits.*.author.email ==>" ${COMMIT_EMAIL}
            echo "github.event.commits.*.author.name ==>" ${COMMIT_NAME}
            echo "github.event.pull_request.head.ref ==>" ${PR_HEAD_REF}
            echo "github.event.pull_request.head.label ==>" ${PR_HEAD_LABEL}
            echo "github.event.pull_request.head.repo.default_branch ==>" ${PR_DEFAULT_BRANCH}
            echo "github.head_ref ==>" ${HEAD_REF}
            echo "github.ref ==>" ${REF}
            echo "github.repository ==>" ${REPO}
            echo "=========================================================================="
            echo "github.event ==>"  ${EVENT}
            echo "=========================================================================="
            printenv
            echo "==========================================================================="
