name: "Print Github Ref"
on:
  push:
  workflow_dispatch:
  pull_request:
jobs: 
    trigger-integration-tests:
      name: Print Ref
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
          env:
            TOKEN: ${{ secrets.TOKEN }}
        - name: Trigger Test run
          env:
            TOKEN: ${{ secrets.TOKEN }}
          run: |
            # Run
            echo "github.head_ref ==>" ${{ github.ref }}
